PP-11681 Replace ‘base-client’ with ‘axios-base-client'
alphagov/pay-selfservice pull request #4185
Opened 2024-02-28 16:22 UTC by JFSGDS

https://payments-platform.atlassian.net/browse/PP-11681

## WHAT

- Change ‘webhooks.client’ methods to use ‘axios-base-client’ library.
- Refactor call parameters initialisation.
- Use ‘async/await’ syntax.

## HOW 
All automated tests should pass without the need to be amended.
Existing functionality should remain unaffected.

2024-02-29 13:00 UTC, iqbalgds requested changes
Looks good - left one comment

2024-02-29 16:17 UTC, JFSGDS commented on app/services/clients/webhooks.client.js
> -      ...options.status && { status: options.status.toUpperCase() }
Good spot Iqbal. Change made as requested.

2024-03-12 17:14 UTC, iqbalgds commented on app/services/clients/webhooks.client.js
> -      ...options.status && { status: options.status.toUpperCase() }
Good work - resolving comment.

2024-03-13 09:18 UTC, iqbalgds approved these changes
Good work - we should get another pair of eyes to check this PR or the ledger client one.  Before rolling out these changes across all the self service clients.

2024-03-27 10:36 UTC, iqbalgds approved these changes
LGTM

2024-03-27 11:42 UTC, merged